### ISSUE TITLE
renaming as game-analytics-ai instead of game-datasets

### ISSUE THREAD

**Issue by mostafatouny** [leomaurodesenv/game-datasets#4]
I believe this repository should be renamed Game Analytics and AI, as it is not just restricted to Game data-sets

**Comment by leomaurodesenv** [comment]
Hello @mostafatouny , 

First of all, thanks for your contribution. 
I really agree with it. In the beginning, it was only datasets.. but now is more than it.

Unfortunately, I cannot change the name because change the link - This repository was shared in some other places.
