### ISSUE TITLE
Paid Market Research Reports

### ISSUE THREAD

**Issue by mostafatouny** [leomaurodesenv/game-datasets#7]
I found the following market research reports related to video-games industry. Even though they are of great value to a data scientist, They are accessed only through payment. I am not sure whether including them is suitable

- [statista, video games](https://www.statista.com/topics/868/video-games/)
- [euro monitor, video games](https://www.euromonitor.com/video-games)
- [new zoo](https://newzoo.com/)
- [grand view research, digital media](https://www.grandviewresearch.com/industry/digital-media)

**Comment by leomaurodesenv** [comment]
Hello @mostafatouny ,
First of all, thanks for be an active member of this repository!

I agree that this is useful content for games/ai but we especifically determine free to use, or open source projects.
Any way, I really think it that this content can be useful for the community.

Thus, I proposed to change the [CONTRIBUTING file](https://github.com/leomaurodesenv/game-datasets/blob/master/CONTRIBUTING.md), and add this content as a new topic, something like "industry insights". What do you think?

**Comment by mostafatouny** [comment]
@leomaurodesenv,
I am delighted to be part of this great repository. Thank you for your kind words.

I totally agree to change _CONTRIBUTING_ and add this content. Let me know whether there is any thing I could do to support that change

**Comment by leomaurodesenv** [comment]
You can propose a pull request. 
After that, I will reorder some sections - as "Books" isn't in alphabetical order, I also modify the _CONTRIBUTING_.
